### ISSUE TITLE
Adicionar linting de código

### ISSUE THREAD

**Issue by ghost** [rocketseat-content/youtube-crawler-codedrops#1]
Boa tarde, me chamo José. Pode ignorar essa issue se quiser, nem sei se é realmente necessário.
Vocês poderiam adicionar o eslint ao projeto ou adotar um dos padrões. Dei uma passada rápida e vi, por exemplo, que foi colocado ponto e vírgula em algumas instruções mas em outras não. Grande abraço!

**Comment by jpedroschmitz** [comment]
Olá, é possível sim. Se quiser subir uma PR, ficarei feliz em aprovar.
